[CI-CD Refactor] Fix onnruntime and deepsparse output validation bug
neuralmagic/sparsezoo pull request #157
Opened 2022-05-26 13:41 UTC by dbogunowicz

The `input_samples.files` and `output_samples.files` lists, by default, were not in-sync e.g.
`input_samples.files -> ['inp-004.npz', 'inp-016.npz', 'inp-006.npz' ...]
`output_samples.files -> ['out-003npz', 'out-006.npz', 'out-007.npz' ...]

Sorting the numpy files solves the problem.

2022-06-06 16:08 UTC, bfineran reviewed
new class looks clean, few comments

2022-06-07 14:06 UTC, dbogunowicz commented
@bfineran yeah, with the new class for validations, I am already a bit more lightweight on the `model_directory.py`, but moving the runner to a separate file is tempting. will do.

2022-06-07 14:47 UTC, bfineran approved these changes

2022-06-07 16:46 UTC, merged

2022-06-07 17:15 UTC, rahul-tuli requested changes
A bunch of nits, with a potential bug

2022-06-08 06:31 UTC, dbogunowicz commented on src/sparsezoo/v2/inference_runner.py
> +        from deepsparse import compile_model
Yes, this was already caught by @KSGulin and fixed. But good catch.

2022-06-08 06:32 UTC, dbogunowicz commented on src/sparsezoo/v2/inference_runner.py
> +        self.engine_type_to_iterator = {
Good catch, I will address that.

2022-06-08 06:33 UTC, dbogunowicz commented on src/sparsezoo/v2/inference_runner.py
> +        self.supported_engines = supported_engines
valid point