Sparse Zoo python apis
neuralmagic/sparsezoo pull request #2
Opened 2020-12-23 19:49 UTC by kevinaer

- Added python api for searching sparse zoo models
- Added python apis for downloading sparse zoo models

2020-12-28 17:25 UTC, bfineran reviewed
code LGTM, just a few nits

2020-12-28 17:43 UTC, markurtz requested changes

2020-12-30 18:57 UTC, markurtz approved these changes

2020-12-30 19:01 UTC, bfineran approved these changes

2020-12-30 19:59 UTC, merged