Comprehensive SparseZoo tests
neuralmagic/sparsezoo pull request #24
Opened 2021-01-30 00:35 UTC by kevinaer

Added tests capturing all models currently deployed. By default only a small subset run but which model tests run can be configured by setting:
- `SPARSEZOO_TEST_ALL_{MODEL}` to run all tests for a specific model architecture
- `SPARSEZOO_TEST_ALL_{SUB_DOMAIN}` to run all tests under a specific sub domain
- `SPARSEZOO_TEST_ALL_MODELS` to run all tests

2021-01-30 01:33 UTC, bfineran submitted a review, later dismissed
LGTM. Is the default behavior that users need to enable the tests they want to run? Or will all run by default?

2021-02-02 12:35 UTC, markurtz requested changes
Testing the helpers is good, but we aren't planning on having helper functions for every model in the zoo. We should have a generic test that uses search models and validates all of the models returned in the search. This function would be an extensive test.

Also, I'm trying to move us away from environment variables for controlling the tests and instead go through pytests's setup for ignoring files and directories. In this way there isn't any potentially hidden state to the user when running make test and it's a bit easier to document. See the sparseml makefile for the latest on that

2021-02-02 19:06 UTC, markurtz submitted a review, later dismissed

2021-02-02 23:41 UTC, markurtz submitted a review, later dismissed

2021-02-03 00:04 UTC, bfineran approved these changes

2021-02-03 03:42 UTC, markurtz approved these changes

2021-02-03 03:51 UTC, merged