Zoo functions for loading recipes and base checkpoint weights from stubs
neuralmagic/sparsezoo pull request #37
Opened 2021-02-13 00:34 UTC by bfineran

intended use cases:
* load recipe from stub instead of local file. (i.e. `ScheduledModifierManager.from_yaml("zoo:/model/stub/path")`)
* get the base weights for a recipe ("base-none" weights for a user trying to reproduce pruning results, and the final model optimized weights for transfer learning)

2021-02-13 17:16 UTC, markurtz approved these changes

2021-02-15 13:40 UTC, markurtz requested changes

2021-02-15 13:40 UTC, markurtz commented on src/sparsezoo/models/zoo.py
> +_ZOO_STUB_PREFIX = "zoo:"
Small thing, can we declare this as public and export it so other integrations can use it explicitly?

2021-02-16 02:51 UTC, bfineran commented
updated to support query strings as discussed in https://github.com/neuralmagic/sparseml/pull/72
i.e. `zoo:model/stub/path?recipe_type=transfer`

2021-02-16 17:39 UTC, markurtz approved these changes

2021-02-16 22:21 UTC, mgoin approved these changes

2021-02-16 22:30 UTC, merged