Set model.data chunk size limit to 400mb
neuralmagic/sparsezoo pull request #412
Opened 2024-01-22 10:37 UTC by dbogunowicz

2024-01-22 14:44 UTC, mgoin commented
@bfineran @markurtz this seems quite small, i would recommend at least a few gigabytes, if not the relatively standard 10GB used in HF

2024-01-22 14:49 UTC, rahul-tuli commented
I thought we were splitting the model into data files if it was >400mb and not restricting the model.data file(s) sizes? The only restriction on model.data file sizes is for easier download/upload from/to sparsezoo for which 400mb seems small? Thoughts?

2024-01-22 15:59 UTC, bfineran requested changes
noting we shouldn't be updating chunk size here as discussed via slack - @dbogunowicz is aware of changes

2024-01-23 12:47 UTC, dbogunowicz commented
@alexm-nm just giving you the heads up, that splitting the external data is now part of the save_onnx function

2024-01-24 15:13 UTC, bfineran commented on src/sparsezoo/utils/onnx/external_data.py
> +            f"{DUMP_EXTERNAL_DATA_THRESHOLD / 1e9} GB"
wrong threshold - also let's downgrade from warning - probably a bit to scary for an expected, default flow

2024-01-24 15:20 UTC, dbogunowicz commented on src/sparsezoo/utils/onnx/external_data.py
>          _LOGGER.warning(
```suggestion
        _LOGGER.debug(
```

2024-01-24 15:22 UTC, dbogunowicz commented on src/sparsezoo/utils/onnx/external_data.py
> +            f"{DUMP_EXTERNAL_DATA_THRESHOLD / 1e9} GB"
```suggestion
            f"{max_external_file_size / 1e9} GB"
```

2024-01-24 15:23 UTC, bfineran approved these changes

2024-01-24 15:57 UTC, merged