Get Path Intergation
neuralmagic/sparsezoo pull request #55
Opened 2021-03-26 20:43 UTC by kevinaer

- Added get path for obtaining a model
- Moved model specific requests to  `download_model_get_request` and `search_model_get_request` to make former method a generic subpath e.g. recipes
- Added `download_model` and `download_model_from_stub` to directly download a model when returning the model isn't necessary. 
- Changed `load_model` and `load_model_from_stub` to use `get_model_get_request` for obtaining faster

2021-03-26 21:22 UTC, bfineran approved these changes, later dismissed
LGTM. I like the decoupling of the existing download_get_request with model downloads.

2021-03-30 17:56 UTC, markurtz requested changes

2021-03-30 17:56 UTC, markurtz commented on src/sparsezoo/requests/download.py
> +    :param sub_path: the sub path from the model path if any
can we give a bit more of an explanation for when this would be used?

2021-03-31 16:35 UTC, markurtz commented on src/sparsezoo/main.py
> +        dir_path = Zoo.download_model(
Should update the variable and potentially the print statement since we're returning a model here again

2021-03-31 18:12 UTC, markurtz approved these changes

2021-03-31 18:43 UTC, bfineran approved these changes

2021-03-31 18:45 UTC, merged