Sparsezoo Script Update and Notebook
neuralmagic/sparsezoo pull request #7
Opened 2021-01-13 16:42 UTC by kevinaer

- Added model_repo notebook
- Fixed bug when forcing model download on unsigned
- Added sparsezoo as a command after pip install
- Changed search output to be more human readable:
```
1) Mnist
-------------------------
Model Description: Pruned Mnist.

Framework: keras

Repository: sparseml

Tags: pruned, Mnist, conservative, mnist, keras, sparseml

Download Command: sparsezoo download --domain cv --sub-domain classification --architecture mnist --framework keras --repo sparseml --dataset mnist --optim-name pruned --optim-category conservative

2) Mobilenet V1
-------------------------
Model Description: Standard MobileNet architecture with width=1.0 trained on the Imagenet dataset. Baseline model: 70.9% for validation top1 accuracy

Framework: pytorch

Repository: sparseml

Tags: mobilenet, base, mobilenet v1, sparseml

Download Command: sparsezoo download --domain cv --sub-domain classification --architecture mobilenet_v1 --sub-architecture 1.0 --framework pytorch --repo sparseml --dataset imagenet --optim-name base --optim-category none

```

2021-01-13 16:53 UTC, bfineran reviewed
Overall LGTM.  What is the difference between main.py and the file in the scripts/ directory? Also can you add Jeannie to the reviewers for the notebook?

2021-01-19 14:36 UTC, markurtz requested changes

2021-01-19 20:27 UTC, bfineran requested changes
Looks good to me pending the comments

2021-01-19 21:26 UTC, bfineran approved these changes

2021-01-19 22:18 UTC, markurtz approved these changes

2021-01-19 23:31 UTC, merged